#!/bin/bash
#
# iptables Default Set Up Script
#
# Flush all current rules
        iptables -F
        iptables -X
        iptables -t nat -F
        iptables -t nat -X
        iptables -t mangle -F
        iptables -t mangle -X
        iptables -P INPUT ACCEPT
        iptables -P FORWARD ACCEPT
        iptables -P OUTPUT ACCEPT
#
#
# Allow localhost connections
        iptables -A INPUT -i lo -j ACCEPT
#
# Allow Established and Related connections
        iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
#
# Allow all Local Area Network connections
        iptables -A INPUT -s 192.168.1.0/24 -j ACCEPT
        iptables -A INPUT -s 172.245.142.173 -j ACCEPT
        iptables -A INPUT -s 192.185.80.246 -j ACCEPT
        iptables -A INPUT -s 173.227.74.5 -j ACCEPT
        iptables -A INPUT -s 70.113.24.50 -j ACCEPT
        iptables -A INPUT -s 99.17.192.133 -j ACCEPT

# Drop all other INPUT
        iptables -P INPUT DROP
#
# Drop all FORWARDED packets
        iptables -P FORWARD DROP
#
# Allow all OUTPUT
        iptables -P OUTPUT ACCEPT
#
# Save Settings
        /sbin/service iptables save
#
# Display default rules
        iptables -L -v
# Echo Done
        echo -e "\nDONE!"

