#!/bin/bash
realusernum=`ps -t ? S | grep "priv" -c`
hostn=`hostname`
date +"%A %B %d %I:%M %p %Z (%:z) %Y [%s]"
uptime
echo -e "--------------------------------------------------------------------------------\n"
echo -e "--------------------------------------------------------------------------------\n"
echo -e "Current SSH Sessions: $realusernum\n"
echo -e "PID   TTY (?)  STAT   CPU  USERNAME@PROCESS"
ps -t ? S | grep ssh | grep "@"
echo -e "Login sessions with an active shell:"
echo -e "USER     TTY      FROM              LOGIN@   IDLE   JCPU   PCPU WHAT"
w -h
echo -e "--------------------------------------------------------------------------------\n"
df -h 
echo -e "--------------------------------------------------------------------------------\n"
free -m -t
echo -e "--------------------------------------------------------------------------------\n"
echo -e "Network Status:"
netstat -s | grep 'connections established'
echo -en "--------------------------------------------------------------------------------\n"
